### PR TITLE
59 welcome page

### PR DESCRIPTION
**Pull request by furilo**
Partially solves #59

### CODE REVIEW

**Comment by furilo** [comment]
@nobuti take a look at the CTA, and include your suggestions in the PR ;)

**Comment by nobuti** [comment]
Done! I've put the same cta button for logged and no logged users, it felt weird being different. Thoughts?

**Comment by furilo** [comment]
Hey, I've gone ahead and styled a bit the buttons, also simplifying the class. We can now just use .button, or <button>'s. Tell me what you think and make the adjustments you feel!

**Comment by nobuti** [comment]
Perfect! :rocket:

**Comment by ferblape** [comment]
Released!

**Pull request merged**
