### PR TITLE
Add countries attribute to model Project

### PR DESCRIPTION
**Pull request by ferblape**
This PR implements #92 and adds a new attribute `countries` to the model Project.

- I have updated the seeds with a few countries
- I have added the list of projects into the form of new / edit project and a filter in the projects page

This attribute requires that we use PostgreSQL as the default database. Therefore, I have updated the `config/database.yml.example` file. If you need help to install Postgres just ping me.

As a curiosity we can't set the `#id` in the seeds file as before. It caused a problem that took me 30 min to debug.

### CODE REVIEW

**Comment by furilo** [comment]
In projects home, Country dropdown, maybe better a list? Once we have projects from more than +15 countries we can think of the dropdown...

**Comment by furilo** [comment]
I added the list (leaving the dropdown commented for when we have to used it). Another issue: the countries list is being ordered by the ISO code, but does not corresponds to the human name... Don't know how to fix that!

**Comment by ferblape** [comment]
Fixed!

**Comment by furilo** [comment]
it seems we lost the global?

**Comment by ferblape** [comment]
Yep, I'll fix it.

**Comment by ferblape** [comment]
Fixed, and I have also added a link to clear the Categories filter.

**Pull request merged**
