### PR TITLE
Link twitter accounts for login

### PR DESCRIPTION
**Pull request by ferblape**
This PR implements a part of #7. Please, check the wording, how I have organized the user's profile and that I haven't added any style in the login page. Also, keep in mind that:

- only Twitter has been integrated
- only can be used to log in the app

If we like how it works / looks, we can add Facebook and / or other services and think about integrating the signup with an external service and get rid of the invitations thing.

One thing to keep in mind: the secrets has been updated with Twitter tokens. I've already updated the secrets file in production, so it can be released safely.

### CODE REVIEW

**Comment by furilo** [comment]
:+1: I've left some comments in the issue.

**Comment by ferblape** [comment]
Facebook integration added

**Comment by ferblape** [comment]
Signup with Twitter and Facebook added. Only auto-adding friends is missing.

**Comment by furilo** [comment]
Aweeeesome. 

- When signing in with a service, if the email exists, the sign up form is presented to the user saying that the email already exists. Would it be possible (I think it makes more sense) to ask the user to sign in instead?
- Have you deleted the "Invite a friend" link for any special reason? Although we'll do the services-friends thing, we may leave the normal email invite, wouldn't you?

**Comment by furilo** [comment]
Another thing: Facebook gives you the user's email, so we need to ask for it after the connect?

**Comment by ferblape** [comment]
- I have restored the invitations (but now they are not mandatory to signup)

- I have fixed the Facebook linking to don't require an email

- if the user introduces an email that already exists we suggest to login and link the account in the profile (it's the simplest thing)

I'm blocked adding users automatically, because I'm trying to get all the twitter / facebook ids in the database with a single query (with postgres everything is possible!).

**Comment by furilo** [comment]
Some of the copy modifications would be addressed in #112. Should we add that in this PR or we open another one (when its discussed)?

**Comment by ferblape** [comment]
I'd add a new one, because this is getting quite big.

**Comment by ferblape** [comment]
BTW, I have completed everything. Ready to be accepted again!

**Pull request merged**
