### PR TITLE
Search in lower case.

### PR DESCRIPTION
**Pull request by nobuti**
This PR implements #99.

### CODE REVIEW

**Comment by ferblape** [comment]
Thanks @nobuti! This is ok for the moment, but in #92 I'm making postgres the default database in development too, because we are starting to use some features that are exclusive to it. And we should migrate the search to the proper full-text search.

**Comment by nobuti** [comment]
ILIKE then?

**Comment by ferblape** [comment]
Nop: http://textacular.github.io/textacular/

**Comment by nobuti** [comment]
With that name, it should be javascript at least.

**Pull request merged**
