### PR TITLE
Modal for signin/signup/social login

### PR DESCRIPTION
**Pull request by furilo**
This addresses #112. Be ware that the new js/css is a bit of a mess :S (I guess I should be doing these things ;) But it seems it works.

Pending that I'm aware of

- [x] Cleanup old forms (sign in, signup, recover password). I guess we could get rid of them, but we should 
- [x] If you fire the modal, fill email+pass for login, and hit enter, you get shown another form; it should just submit the form
- [ ] In the header we have two links (signup, login), the two do the same, we could unify in one

@ferblape as I said, I think I forked this from the right branch so we have all recent improvements.

### CODE REVIEW

**Comment by ferblape** [comment]
Looks like the branch is correct. I'll review it.

**Comment by ferblape** [comment]
Because we have lost all the error messages in login/signup/reset_password forms I have introduced a flash message when the form submitted contains errors, and also it opens automatically the modal:

screen shot 2015-03-12 at 08 46 50

I still need to do some stuff apart from what you mentioned:

- [ ] deal with invitations in the new signup form
- [ ] there's a superweird performance issue and loading the homepage takes 1 second in the server. I'm checking it.
- [ ] fix all the specs that relay on the old login form to login in Trackdons

**Comment by furilo** [comment]
BTW any special reason for disabling Turbolinks? UX-wise, I would leave it.

**Comment by ferblape** [comment]
Hey @nobuti I need your help in this branch, because I'm not able to find the bug.

If you go to the page of a project, the new donations form don't show the current project name in the form, even though if you click on the list of projects, it's selected. So I guess is something with the CSS or a parameter from select2 that I can't find.

Here's an screenshot:

screen shot 2015-03-14 at 18 17 12

**Comment by nobuti** [comment]
Oh I'll take a look.

**Comment by ferblape** [comment]
Thanks Buti. Now I'm thinking that we might just deactivate the select2 in
that page, because we don't want the user change the project to donate to.

**Comment by nobuti** [comment]
I'm fixing the issue, then I'll change it to a simple text field. Maybe disabled?

**Comment by nobuti** [comment]
Something odd in that page: `@project == @donation.project` es `false`. Should not they be the same?

**Comment by nobuti** [comment]
I think the issue is that form is rendered as new donation, it should be rendered in edition mode.

**Comment by ferblape** [comment]
I'll take a look later. I have pushed some commits that integrate recurring donations. Take care with the conflicts!

**Comment by ferblape** [comment]
Guys, this is ready to be accepted again. Thanks @nobuti for your help.

There are a couple of things that we need to implement but they are not so important and I'd open new issues:

- when you sign up / login with Twitter or FB you are not redirected to the current page

- we should show the recurring donations a user has. Right now, when you create a recurring donation I redirect the user to the last donation generated by that recurring donation. We need to improve that too.

I know this has been quite special because we have all the new CSS, but we should try to make smaller PR in the future, in order to not blocking to the rest of the people.

**Comment by furilo** [comment]
OK, I'm seeing some things but if you want we can merge this PR and continue working with new issues. OK?

**Comment by ferblape** [comment]
:+1:

Merged and released! Feel free to create some issues. I'll review everything in production today and I'll create a few too.

**Comment by nobuti** [comment]
:fireworks:

**Pull request merged**
