### PR TITLE
122 responsive donation form - WIP (don't merge yet)

### PR DESCRIPTION
**Pull request by furilo**
Hey @nobuti I have merged your changes with other things we just did. I have adjusted some other responsive issues. You can take a look at the modal that launches the donation tracking form. Regarding design for responsive, I'd say justify elements where possible or make full width where it makes sense.

Also please take a look at how I have started using the responsive mixin with the breakpoint and tell me if you think this is the right way, or point me in the right direction ;) 

(also, I create the PR so we can look at changes easily)

### CODE REVIEW

**Comment by nobuti** [comment]
All makes sense! :+1: 

It's fine to use the mixin like that, but usually you will want to use in a mobile first mode. This is:
```
.component {
    // mobile rules here
   
   @include min-screen(480) {
      // This code works from 480 to 779
   }

   @include min-screen(780) {
      // This code works from 780 to the moon
   }
}
```
This way we can take advantage of the css inheritance. But in this case, it's just a matter of style, because the result it's the same. For me it's more readable.
I'll fine tuned the form asap.

**Comment by furilo** [comment]
@ferblape I want to create a test scenario 'I see the total number of projects I want to donate to'

For that I would need the user to follow a project. Should I create a follow_project method and put it in a support/project_helper.rb? Or which is the right way to do it?

**Comment by ferblape** [comment]
Or just write in the test: `user.follow(project)` after having created the user and the project.

Example:

```ruby
  background do
    Timecop.freeze Time.parse('2014-10-30')

    @project = create_project(name: 'Wikiwadus')
    @user = create_user(name: 'Yorch', password: 'wadusm4n', email: "yorch@example.com")
    @user.follow(@project)
  end
```

**Comment by furilo** [comment]
Hey, I have merged this so we have in production some of the things that were already done ;) Not closing the PR though.

**Pull request merged**
