### PR TITLE
New home

### PR DESCRIPTION
**Pull request by furilo**
WIP. I'm going to try to have the donation tracking form in a modal. Let's see if I can manage to get the error tracking thing right.

#113

### CODE REVIEW

**Comment by ferblape** [comment]
Maybe instead of "No" and "Sí, claro" it could be "Todavía no" and "Sí", because "Sí, claro" sounds like "This is the correct thing", then you are underestimating the other group of people. 

Do you want to put that as the default home or set something like a cookie to don't display it always?

**Comment by furilo** [comment]
Don't we want to understimate, at least a little bit?? ;)

In other order of things, I have committed the tracking form in the modal. I have not managed to have the modal appear when there is an error: I don'f fully understand where/how the first parameter in 

https://github.com/TrackDons/trackdons/pull/120/files#diff-55c5b7aecfb519d0e4880eaf2788eb6eR47

is being used. 

Also, I have done this: 

https://github.com/TrackDons/trackdons/pull/120/files#diff-55c5b7aecfb519d0e4880eaf2788eb6eR6

In order to have the form available in all pages. If this is problematic, I guess we could load the content of the modal with Ajax.

**Comment by ferblape** [comment]
The first parameter is used to pick in which of the three forms the error message should be displayed: [login](https://github.com/TrackDons/trackdons/blob/master/app/views/shared/_modal_login.html.erb#L6), [signup](https://github.com/TrackDons/trackdons/blob/master/app/views/shared/_modal_login.html.erb#L48) or [password_resets](https://github.com/TrackDons/trackdons/blob/master/app/views/shared/_modal_login.html.erb#L48).

Once you set the error the modal is open automatically (in fact the code is duplicated!):

https://github.com/TrackDons/trackdons/blob/master/app/assets/javascripts/modules/modal.js#L23-L25

**Comment by ferblape** [comment]
About the filter, I think it's fine!

**Comment by ferblape** [comment]
Specs fixed

**Pull request merged**
