### PR TITLE
Display donations and recurring donations

### PR DESCRIPTION
**Pull request by ferblape**
This PR is a WIP for #116

### CODE REVIEW

**Comment by ferblape** [comment]
@furilo: you can start integrating styles in the donations lists. 

Still pending:

* [ ] tests
* [ ] fix links to Edit and Delete donation

**Comment by ferblape** [comment]
I have changed a bit the approach to implement Recurring Donations, because I realized that it wasn't necessary to have to models, and that recurring donations are just a kind of donation. The code is much cleaner and I have removed some duplication that was annoying me.

The PR includes a migration that moves all the data to the Donation model.

**Comment by ferblape** [comment]
Hey maybe I wasn't clear enough. This PR is not a WIP anymore and can be accepted and merged

**Comment by furilo** [comment]
@ferblape for my part ready to merge!

**Pull request merged**
